### ISSUE TITLE
Documentation for stateActions

### ISSUE THREAD

**Issue by austincondiff** [xyflow/react-flow-docs-v9#1]
I can't find usage docs for `updateNodePos` for example. Please provide docs for each action.

**Comment by chrtze** [comment]
The actions from the store are more like an unofficial way to manipulate the internal state of react flow. These actions might also change in the future. Anyway, the best way to get an overview of the actions and their usage is in the source of the store directly: https://github.com/wbkd/react-flow/blob/main/src/store/index.ts#L96-L151
